src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Applied_Payment_Total__c</fullName>
        <description>Stores the amount of all applied Payment(s) to a Project(s) by this Contact.</description>
        <inlineHelpText>This amount reflects the total amount of all applied payments to a project that this Contact has made.</inlineHelpText>
        <label>Applied Payment Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <description>Stores the date of the most recently applied Payment.</description>
        <inlineHelpText>This value reflects the most recently applied payment date for this Contact.</inlineHelpText>
        <label>Last Payment Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Stores related payment information for payment(s) applied to Project(s) (Project__c).</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the applied payment.</description>
        <inlineHelpText>The amount of the applied payment.</inlineHelpText>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the related Contact record that applied the Payment.</description>
        <inlineHelpText>The Contact who has applied the Payment.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <description>Captures the date/time that the payment was applied.</description>
        <inlineHelpText>The date that the payment was applied to the project.</inlineHelpText>
        <label>Payment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Stores the related Project to this Payment.</description>
        <inlineHelpText>Stores the related Project to this Payment.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>Stores related project information for project(s) related to Contact and/or payment (Payment__c).</description>
    <fields>
        <fullName>Applied_Payment_Total__c</fullName>
        <description>Calculated total amount of all Payment(s) that have been applied to this Project.</description>
        <inlineHelpText>This amount reflects the total amount of all payments that have been applied to this project.</inlineHelpText>
        <label>Applied Payment Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactDataService.cls
/**
 * ContactDataService.cls
 *
 * @abstract Data service class for exposing CRUD operations on the Contact object.
 *
 * @author Chase Logan
 */
public class ContactDataService extends BaseDataService {

	/**
	 * Get all Contacts that have made at least one Payment to any Project as a child collection. 
	 * Limited to 1000 records as you can't display more than that in an apex:repeat without a 
	 * readonly page, as well as modified in the last two years, for sake of performance :)
	 *
	 * @return List of Contacts with associated List of Payment records
	 */
	public List<Contact> getContactsWithAppliedPayments() {
		
		List<Contact> returnVal;

		try {

			returnVal = [select Id, Name, Applied_Payment_Total__c, Last_Payment_Date__c,
								( select Id, Name, Amount__c, Payment_Date__c, Contact__c,
										 Project__c, Project__r.Name, Project__r.Applied_Payment_Total__c
								    from Payments__r
								   where Project__c != null
								     and LastModifiedDate = LAST_N_DAYS:730
								order by CreatedDate desc)
						   from Contact
						  limit 1000];

		} catch ( DmlException de) {

			Util.debug( de.getStackTraceString(), de.getLineNumber(), de.getMessage());
		} catch ( Exception e) {

			Util.debug( e.getStackTraceString(), e.getLineNumber(), e.getMessage());
		}

		return returnVal;
	}

}